### ISSUE TITLE
How to exclude a page from Sitemap

### ISSUE THREAD

**Issue by SciCrea** [vdlp/oc-sitemapgenerators-plugin#1]
Hi, very good that the plugin automatically generates Sitemap. Thank you! But it includes pages: 404, error and other unnecessary pages. How can I be excluded?

**Comment by adrenth** [comment]
This is actually documented here:
https://github.com/vdlp/oc-sitemap-plugin/blob/master/README.md#exclude-urls-from-sitemap

Good luck! If you have any questions, please let me know.
