### ISSUE TITLE
Plugin doesn't install

### ISSUE THREAD

**Issue by kff5000** [vdlp/oc-sitemapgenerators-plugin#4]
Hello,

after installing vdlp-sitemap, installing vdlp-sitemapgenerators doesn't work (using october 3.3.12):

<img width="460" alt="2023-05-09 13_34_48-Marketplace _ October CMS" src="https://github.com/vdlp/oc-sitemapgenerators-plugin/assets/45714336/887487cf-35e2-494c-b8c8-ee36b6c3d35f">
<img width="689" alt="2023-05-09 13_35_23-Marketplace _ October CMS" src="https://github.com/vdlp/oc-sitemapgenerators-plugin/assets/45714336/1a3afa2d-2fa3-4baf-9277-94f6cc2935f3">

**Comment by adrenth** [comment]
Hi @kff5000, this issue should be resolved. Please install the latest versions of the plugins.
